--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023.02.07. 11:31:18
-- Server version: 5.5.5-10.4.24-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS taxi6;

CREATE DATABASE IF NOT EXISTS taxi6
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE taxi6;

DELIMITER $$

--
-- Create function `randInt`
--
CREATE DEFINER = 'root'@'localhost'
FUNCTION IF NOT EXISTS randInt(min int, max int)
  RETURNS int(11)
BEGIN

set @rand = FLOOR( RAND() * (max-min + 1) + min);
RETURN @rand;
END
$$

--
-- Create function `randLicense`
--
CREATE DEFINER = 'root'@'localhost'
FUNCTION IF NOT EXISTS randLicense(carName varchar(255))
  RETURNS varchar(255) CHARSET utf8 COLLATE utf8_hungarian_ci
BEGIN
set @firstChar = left(carName, 1);
set @licenceNumber = concat(@firstChar,@firstChar,randInt(100,999));
RETURN @licenceNumber;
END
$$

--
-- Create function `randCar`
--
CREATE DEFINER = 'root'@'localhost'
FUNCTION IF NOT EXISTS randCar()
  RETURNS varchar(255) CHARSET utf8 COLLATE utf8_hungarian_ci
BEGIN
set @car = ELT(randInt(1,5),'Mercedesz','Fiat','BMW','Volvo','Toyota');
RETURN @car;
END
$$

DELIMITER ;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `cars`
--
CREATE TABLE IF NOT EXISTS cars (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  licenceNumber VARCHAR(10) DEFAULT NULL,
  hourlyRate INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1001,
AVG_ROW_LENGTH = 655,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `trips`
--
CREATE TABLE IF NOT EXISTS trips (
  id INT(11) NOT NULL AUTO_INCREMENT,
  numberOfMinits INT(11) DEFAULT NULL,
  date DATETIME NOT NULL,
  carId INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 259,
AVG_ROW_LENGTH = 104,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE trips 
  ADD CONSTRAINT FK_trips_cars_id FOREIGN KEY (carId)
    REFERENCES cars(id);

DELIMITER $$

--
-- Create procedure `genStat`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE genStat()
BEGIN

DELETE
  FROM trips;
DELETE
  FROM cars;
DELETE
  FROM users;

INSERT cars (id, name, licenceNumber, hourlyRate)
  VALUES (1, 'Mercedesz', 'MM123', 2500),
  (2, 'Fiat', 'FF123', 3500),
  (3, 'BMW', 'BB123', 2900);

INSERT trips (numberOfMinits, date, carId)
  VALUES (23, '2022.12.13 12:00:00', 1), (15, '2022.12.13 13:20:00', 1),
  (29, '2022.12.13 12:00:00', 2), (10, '2022.12.13 14:25:00', 2), (41, '2022.12.13 20:15:00', 2),
  (10, '2022.12.13 12:00:00', 3), (18, '2022.12.13 13:25:00', 3), (22, '2022.12.13 18:15:00', 3);


INSERT users (id, email, password)
  VALUES (1, 'x@gmail.com', 'xjeszó'), (2, 'y@gmail.com', 'yjeszó'), (3, 'z@gmail.com', 'zjeszó');

SELECT
  *
FROM cars;
SELECT
  *
FROM trips;
SELECT
  *
FROM users;

END
$$

--
-- Create procedure `genDin`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE genDin(IN carNumber int, dateValue varchar(255), tripCountMin int, tripCountMax int)
BEGIN

DELETE
  FROM trips;
DELETE
  FROM cars;
DELETE
  FROM users;

SET @a = 0;
simple_loop: LOOP
   SET @a=@a+1;

    # véletlen car
    set @c = randCar();
INSERT cars (id, name, licenceNumber, hourlyRate)
  VALUES (@a, @c, randLicense(@c), randInt(1000, 2500));


#trips-ek
    set @t = 1;
    set @deltaMinits = 0;
    set @tripsCount =  randInt(tripCountMin, tripCountMax);
    trips_loop: LOOP 
       
       set @numberOfMinits =  randInt(15, 60);
 #eddig tart egy fuvar
       set @pauseMinits = randInt(0, 60);
 #várakozási idő a következő fuvarig
       set @deltaMinits =  @deltaMinits + @numberOfMinits + @pauseMinits;
#TIMESTAMPADD(MINUTE, @deltaMInits), dateValue)

#trips készítése

INSERT trips (numberOfMinits, date, carId)
  VALUES (@numberOfMinits, TIMESTAMPADD(MINUTE, @deltaMinits, dateValue), @a);

       SET @t=@t+1;
       IF @t>@tripsCount THEN
          LEAVE trips_loop;
       END IF;
    END LOOP trips_loop;



   
   IF @a>=carNumber THEN
      LEAVE simple_loop;
   END IF;
END LOOP simple_loop;

SELECT
  *
FROM cars;
SELECT
  *
FROM trips;
SELECT
  *
FROM users;

END
$$

--
-- Create procedure `procedure1`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE procedure1()
BEGIN

END
$$

DELIMITER ;

-- 
-- Dumping data for table cars
--
INSERT INTO cars VALUES
(1, 'Mercedesz', 'MM224', 1195),
(2, 'Fiat', 'FF498', 1677),
(3, 'BMW', 'BB690', 2149),
(4, 'Toyota', 'TT313', 1914),
(5, 'Fiat', 'FF734', 1733),
(6, 'BMW', 'BB311', 1657),
(7, 'BMW', 'BB583', 1597),
(8, 'Mercedesz', 'MM394', 1304),
(9, 'Fiat', 'FF755', 1732),
(10, 'BMW', 'BB903', 1267),
(11, 'BMW', 'BB278', 2007),
(12, 'Volvo', 'VV990', 1828),
(13, 'BMW', 'BB758', 1023),
(14, 'Volvo', 'VV117', 1315),
(15, 'Volvo', 'VV243', 1941),
(16, 'Toyota', 'TT943', 2344),
(17, 'Fiat', 'FF416', 1200),
(18, 'Volvo', 'VV707', 1594),
(19, 'BMW', 'BB699', 1174),
(20, 'Mercedesz', 'MM230', 1647),
(21, 'Mercedesz', 'MM958', 1932),
(22, 'Mercedesz', 'MM768', 1872),
(23, 'Volvo', 'VV270', 2387),
(24, 'Toyota', 'TT779', 1516),
(25, 'Toyota', 'TT862', 1791);

-- 
-- Dumping data for table users
--
-- Table taxi6.users does not contain any data (it is empty)

-- 
-- Dumping data for table trips
--
INSERT INTO trips VALUES
(102, 51, '2022-11-12 13:08:00', 1),
(103, 15, '2022-11-12 13:36:00', 1),
(104, 17, '2022-11-12 14:32:00', 1),
(105, 16, '2022-11-12 15:04:00', 1),
(106, 27, '2022-11-12 13:05:00', 2),
(107, 28, '2022-11-12 14:06:00', 2),
(108, 57, '2022-11-12 15:58:00', 2),
(109, 52, '2022-11-12 17:10:00', 2),
(110, 25, '2022-11-12 17:45:00', 2),
(111, 21, '2022-11-12 18:17:00', 2),
(112, 40, '2022-11-12 19:06:00', 2),
(113, 20, '2022-11-12 19:33:00', 2),
(114, 28, '2022-11-12 20:04:00', 2),
(115, 34, '2022-11-12 21:36:00', 2),
(116, 15, '2022-11-12 12:41:00', 3),
(117, 23, '2022-11-12 13:38:00', 3),
(118, 30, '2022-11-12 15:06:00', 3),
(119, 51, '2022-11-12 16:01:00', 3),
(120, 16, '2022-11-12 17:11:00', 3),
(121, 32, '2022-11-12 17:55:00', 3),
(122, 56, '2022-11-12 19:45:00', 3),
(123, 49, '2022-11-12 20:39:00', 3),
(124, 23, '2022-11-12 21:43:00', 3),
(125, 53, '2022-11-12 13:05:00', 4),
(126, 37, '2022-11-12 14:35:00', 4),
(127, 55, '2022-11-12 16:16:00', 4),
(128, 24, '2022-11-12 17:25:00', 4),
(129, 20, '2022-11-12 18:05:00', 4),
(130, 23, '2022-11-12 13:18:00', 5),
(131, 15, '2022-11-12 13:52:00', 5),
(132, 40, '2022-11-12 15:21:00', 5),
(133, 33, '2022-11-12 16:27:00', 5),
(134, 19, '2022-11-12 12:23:00', 6),
(135, 17, '2022-11-12 12:43:00', 6),
(136, 19, '2022-11-12 13:23:00', 6),
(137, 34, '2022-11-12 14:01:00', 6),
(138, 18, '2022-11-12 14:27:00', 6),
(139, 39, '2022-11-12 15:18:00', 6),
(140, 47, '2022-11-12 13:09:00', 7),
(141, 50, '2022-11-12 14:43:00', 7),
(142, 30, '2022-11-12 15:43:00', 7),
(143, 38, '2022-11-12 16:24:00', 7),
(144, 48, '2022-11-12 17:40:00', 7),
(145, 40, '2022-11-12 13:21:00', 8),
(146, 49, '2022-11-12 14:54:00', 8),
(147, 52, '2022-11-12 13:09:00', 9),
(148, 16, '2022-11-12 13:43:00', 9),
(149, 32, '2022-11-12 14:15:00', 9),
(150, 55, '2022-11-12 15:35:00', 9),
(151, 39, '2022-11-12 13:39:00', 10),
(152, 32, '2022-11-12 15:06:00', 10),
(153, 33, '2022-11-12 15:59:00', 10),
(154, 51, '2022-11-12 13:30:00', 11),
(155, 54, '2022-11-12 14:43:00', 11),
(156, 18, '2022-11-12 15:24:00', 11),
(157, 48, '2022-11-12 16:38:00', 11),
(158, 16, '2022-11-12 17:43:00', 11),
(159, 59, '2022-11-12 19:09:00', 11),
(160, 30, '2022-11-12 19:57:00', 11),
(161, 38, '2022-11-12 21:15:00', 11),
(162, 28, '2022-11-12 12:34:00', 12),
(163, 45, '2022-11-12 13:20:00', 12),
(164, 19, '2022-11-12 14:04:00', 12),
(165, 53, '2022-11-12 15:49:00', 12),
(166, 54, '2022-11-12 17:22:00', 12),
(167, 48, '2022-11-12 18:49:00', 12),
(168, 18, '2022-11-12 19:35:00', 12),
(169, 17, '2022-11-12 20:45:00', 12),
(170, 27, '2022-11-12 21:52:00', 12),
(171, 32, '2022-11-12 12:45:00', 13),
(172, 59, '2022-11-12 13:54:00', 13),
(173, 59, '2022-11-12 15:12:00', 13),
(174, 45, '2022-11-12 16:20:00', 13),
(175, 57, '2022-11-12 17:48:00', 13),
(176, 49, '2022-11-12 18:50:00', 13),
(177, 55, '2022-11-12 20:31:00', 13),
(178, 20, '2022-11-12 21:09:00', 13),
(179, 23, '2022-11-12 21:34:00', 13),
(180, 30, '2022-11-12 13:12:00', 14),
(181, 38, '2022-11-12 14:16:00', 14),
(182, 43, '2022-11-12 15:50:00', 14),
(183, 29, '2022-11-12 16:24:00', 14),
(184, 36, '2022-11-12 17:03:00', 14),
(185, 57, '2022-11-12 18:28:00', 14),
(186, 39, '2022-11-12 19:20:00', 14),
(187, 40, '2022-11-12 20:06:00', 14),
(188, 54, '2022-11-12 21:56:00', 14),
(189, 20, '2022-11-12 23:05:00', 14),
(190, 33, '2022-11-12 12:36:00', 15),
(191, 16, '2022-11-12 12:55:00', 15),
(192, 20, '2022-11-12 13:45:00', 15),
(193, 18, '2022-11-12 15:00:00', 15),
(194, 37, '2022-11-12 16:11:00', 15),
(195, 32, '2022-11-12 16:53:00', 15),
(196, 49, '2022-11-12 17:56:00', 15),
(197, 45, '2022-11-12 13:01:00', 16),
(198, 31, '2022-11-12 14:31:00', 16),
(199, 53, '2022-11-12 15:37:00', 16),
(200, 43, '2022-11-12 16:47:00', 16),
(201, 33, '2022-11-12 18:02:00', 16),
(202, 24, '2022-11-12 19:25:00', 16),
(203, 26, '2022-11-12 20:09:00', 16),
(204, 49, '2022-11-12 21:52:00', 16),
(205, 45, '2022-11-12 13:15:00', 17),
(206, 38, '2022-11-12 13:58:00', 17),
(207, 54, '2022-11-12 14:53:00', 17),
(208, 39, '2022-11-12 16:08:00', 17),
(209, 34, '2022-11-12 16:58:00', 17),
(210, 20, '2022-11-12 18:02:00', 17),
(211, 31, '2022-11-12 19:06:00', 17),
(212, 41, '2022-11-12 12:42:00', 18),
(213, 34, '2022-11-12 13:18:00', 18),
(214, 56, '2022-11-12 14:38:00', 18),
(215, 29, '2022-11-12 15:31:00', 18),
(216, 15, '2022-11-12 16:38:00', 18),
(217, 28, '2022-11-12 17:59:00', 18),
(218, 37, '2022-11-12 19:25:00', 18),
(219, 41, '2022-11-12 20:33:00', 18),
(220, 40, '2022-11-12 21:35:00', 18),
(221, 22, '2022-11-12 22:44:00', 18),
(222, 41, '2022-11-12 12:46:00', 19),
(223, 48, '2022-11-12 13:56:00', 19),
(224, 47, '2022-11-12 15:05:00', 19),
(225, 48, '2022-11-12 16:24:00', 19),
(226, 33, '2022-11-12 17:23:00', 19),
(227, 59, '2022-11-12 18:58:00', 19),
(228, 17, '2022-11-12 19:42:00', 19),
(229, 29, '2022-11-12 12:53:00', 20),
(230, 19, '2022-11-12 13:27:00', 20),
(231, 15, '2022-11-12 13:58:00', 20),
(232, 28, '2022-11-12 15:09:00', 20),
(233, 44, '2022-11-12 15:58:00', 20),
(234, 39, '2022-11-12 17:00:00', 20),
(235, 29, '2022-11-12 17:57:00', 20),
(236, 31, '2022-11-12 18:54:00', 20),
(237, 32, '2022-11-12 12:38:00', 21),
(238, 34, '2022-11-12 14:02:00', 21),
(239, 53, '2022-11-12 15:39:00', 21),
(240, 21, '2022-11-12 16:29:00', 21),
(241, 45, '2022-11-12 13:00:00', 22),
(242, 28, '2022-11-12 14:08:00', 22),
(243, 37, '2022-11-12 15:14:00', 22),
(244, 56, '2022-11-12 16:15:00', 22),
(245, 49, '2022-11-12 17:34:00', 22),
(246, 24, '2022-11-12 18:32:00', 22),
(247, 23, '2022-11-12 19:08:00', 22),
(248, 39, '2022-11-12 19:50:00', 22),
(249, 38, '2022-11-12 12:59:00', 23),
(250, 25, '2022-11-12 13:30:00', 23),
(251, 26, '2022-11-12 13:19:00', 24),
(252, 44, '2022-11-12 14:35:00', 24),
(253, 51, '2022-11-12 15:47:00', 24),
(254, 32, '2022-11-12 17:09:00', 24),
(255, 15, '2022-11-12 17:56:00', 24),
(256, 43, '2022-11-12 19:12:00', 24),
(257, 56, '2022-11-12 13:06:00', 25),
(258, 23, '2022-11-12 13:55:00', 25);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;